### ISSUE TITLE
Unit Bug: Since Update

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#29]
**High Priority**
Hi @PascalPadberg, 
On some of our models we are getting failed simulations (see attached log) [Simulation with id 661 failed.txt](https://github.com/tlkenergy/sim-tlk/files/9564147/Simulation.with.id.661.failed.txt)

I found found that this is due to the model output/ variable didn't have a unit assigned from Modelica and therefore we manually assigned it. 
Now it is not allowed to use these manually assigned units. 
The solution I see: If there is no unit assigned; allows any unit to be displayed on the plot. 
<img width="846" alt="image" src="https://user-images.githubusercontent.com/45364510/190096370-a053874c-2ef8-4a87-9ecb-5170bd535bf5.png">

**Comment by PascalPadberg** [comment]
That is already implemented as you describe, if there is no unit in the FMU, you can choose from all the available units.

The compressor power has a unit in this FMU:
![image](https://user-images.githubusercontent.com/46345541/190100445-f3372d51-0037-44dc-84ae-9b4cfb19de90.png)

**Comment by Walshest** [comment]
> 

I am getting an error back from a lot of our models: 
e.g. 
Error: `apps.units.exceptions.UnitsNotCompatible: Origin unit belongs to quantity MoleFraction and target unit to MassFlowRate.`
Model: **TXV_TR6_R404a**
<img width="353" alt="image" src="https://user-images.githubusercontent.com/45364510/190101270-d23009ba-8943-4a81-93e6-a26aeca9c235.png">

**Comment by PascalPadberg** [comment]
Now it works. I had to re-read the model_description of this FMU

**Comment by Walshest** [comment]
> Now it works. I had to re-read the model_description of this FMU

Thanks I confirm this works now, we will have this issue on several other models: 
1. MOPD_ER6
2. OrificeValveEvaporator
4. ETS5M_MOPD

**Comment by PascalPadberg** [comment]
I fixed those, too

**Comment by Walshest** [comment]
Thanks a million . 
All working now :)

**Comment by Walshest** [comment]
The model still isn't working:
 1. MOPD_ER6
: `apps.units.exceptions.UnitsNotCompatible: Origin unit belongs to quantity Time and target unit to MoleFraction.`

**Comment by PascalPadberg** [comment]
The problem with this is that line plots are used with variable "time". This should be done with "timeseries" plots, because the variable "time" is not included in the FMU

**Comment by PascalPadberg** [comment]
I could change the "line" plot to "timeseries" plot for you. So you don't have to recreate them
