### ISSUE TITLE
An error Occured - Messages

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#57]
Hi, 
Over the last 2 weeks users have been reporting that an error message has been popping up on the main front page of Sim.TLK. 

Other than this error message popping up; the tool is working as expected and simulations run. 
<img width="275" alt="image" src="https://github.com/tlkenergy/sim-tlk/assets/45364510/be56bbc1-f48b-4cbb-8acb-0d329d2e6ce5">

**Comment by mateokurti** [comment]
Hi,

It should be resolved now.

Thank you and sorry for the inconvenience.

**Comment by Walshest** [comment]
Hi @mateokurti , 
Unfortunately the issue is still there: 
<img width="916" alt="image" src="https://github.com/tlkenergy/sim-tlk/assets/45364510/ab54d672-8ddb-4f84-8b5d-03b62ce598cb">

**Comment by mateokurti** [comment]
I think it's probably cached on the session. Can you try signing out and logging in again. This should resolve it.

**Comment by Walshest** [comment]
It is solved now. Thanks :)
